version: '3.8'

services:
  frontend:
    image: client:latest
    ports:
      - '3000:3000'
    depends_on:
      - backend

  backend:
    image: server:latest
    ports: 
      - '5000:5000'
    environment:
      -   MONGO_URL=mongodb+srv://admin:admin@cluster0.4qhg3.mongodb.net/rustleup?retryWrites=true&w=majority

