version: '3.8'

services:
  frontend:
    image: frontend:latest
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      local:
        ipv4_address: "192.168.1.8"

  backend:
    image: backend:latest
    ports: 
      - '5000:5000'
    environment:
      -   MONGO_URL=mongodb+srv://admin:admin@cluster0.4qhg3.mongodb.net/rustleup?retryWrites=true&w=majority
    networks:
      local:
        ipv4_address: "192.168.1.5"

networks:
  local:
    ipam:
      driver: default
      config: 
        - subnet: "192.168.1.0/24"
