version: '3.8'

services:
  frontend:
    image: frontend:backend
    ports:
      - '3001:3000'
    depends_on:
      - backend
    networks:
      - test

  backend:
    image: backend:latest
    container_name: backend
    ports: 
      - '5001:5000'
    environment:
      -   MONGO_URL=mongodb+srv://admin:admin@cluster0.4qhg3.mongodb.net/rustleup?retryWrites=true&w=majority
    networks:
      - test

networks:
  test: